name: Deploy to Netlify

on:
  push:
    branches:
      - main  # o usa 'master' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST -d '{}' https://api.netlify.com/build_hooks/682b3d49a79f12211ff26267
